BulkyBookWeb/Controllers/TransactionCategoryModalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BulkyBookWeb.Models;
using BulkyBookWeb.ViewModels;
using bulkybookweb.efcore;
using Microsoft.AspNetCore.Authorization;

namespace BulkyBookWeb.Controllers
{
    public class TransactionCategoryModalController : Controller
    {
        private readonly BulkyContext _context;
        private readonly EFCategoryRepository eFCategoryRepository;

        public TransactionCategoryModalController(BulkyContext context, EFCategoryRepository eFCategoryRepository)
        {
            _context = context;
            this.eFCategoryRepository = eFCategoryRepository;
        }

        // GET: TransactionCategoryModal
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var CategoryList = await eFCategoryRepository.GetAll();
            return View(CategoryList);
        }

        // GET: TransactionCategoryModal/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.CreateCategoryViewModel == null)
            {
                return NotFound();
            }

            var createCategoryViewModel = await _context.CreateCategoryViewModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (createCategoryViewModel == null)
            {
                return NotFound();
            }

            return View(createCategoryViewModel);
        }

        // GET: TransactionCategoryModal/Create
        public async Task<IActionResult> AddorEdit(int id=0)
        {
            if(ModelState.IsValid)
            {
                if (id == 0)
                {
                    return View();
                }
                else
                {
                    var result = await eFCategoryRepository.Get(id);
                    CreateCategoryViewModel model = new CreateCategoryViewModel
                    {
                        Name = result.Name,
                        CreatedDateTime = result.CreatedDateTime,
                        Displayorder = result.Displayorder,
                        ID = result.Id

                    };
                    if (model == null)
                    {
                        return NotFound();
                    }
                    return View(model);
                }
                

            }
            return View();
        }

        // POST: TransactionCategoryModal/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Displayorder,CreatedDateTime")] CreateCategoryViewModel createCategoryViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(createCategoryViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(createCategoryViewModel);
        }

        // GET: TransactionCategoryModal/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.CreateCategoryViewModel == null)
            {
                return NotFound();
            }

            var createCategoryViewModel = await _context.CreateCategoryViewModel.FindAsync(id);
            if (createCategoryViewModel == null)
            {
                return NotFound();
            }
            return View(createCategoryViewModel);
        }

        // POST: TransactionCategoryModal/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Displayorder,CreatedDateTime")] CreateCategoryViewModel createCategoryViewModel)
        {
            if (id != createCategoryViewModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(createCategoryViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CreateCategoryViewModelExists(createCategoryViewModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(createCategoryViewModel);
        }

        // GET: TransactionCategoryModal/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.CreateCategoryViewModel == null)
            {
                return NotFound();
            }

            var createCategoryViewModel = await _context.CreateCategoryViewModel
                .FirstOrDefaultAsync(m => m.ID == id);
            if (createCategoryViewModel == null)
            {
                return NotFound();
            }

            return View(createCategoryViewModel);
        }

        // POST: TransactionCategoryModal/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.CreateCategoryViewModel == null)
            {
                return Problem("Entity set 'BulkyContext.CreateCategoryViewModel'  is null.");
            }
            var createCategoryViewModel = await _context.CreateCategoryViewModel.FindAsync(id);
            if (createCategoryViewModel != null)
            {
                _context.CreateCategoryViewModel.Remove(createCategoryViewModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CreateCategoryViewModelExists(int id)
        {
          return (_context.CreateCategoryViewModel?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

BulkyBookWeb/Views/TransactionCategoryModal/AddorEdit.cshtml
@model BulkyBookWeb.ViewModels.CreateCategoryViewModel

@{
    ViewData["Title"] = "Edit";
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="CreatedDateTime" />
            
           @* <div class="form-group">
                <label asp-for="Displayorder" class="control-label"></label>
                <input asp-for="Displayorder" class="form-control" />
                <span asp-validation-for="Displayorder" class="text-danger"></span>
            </div>*@
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                         <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                   #
                                </div>
                            </div>
                            <input asp-for="Name" class="form-control" />
                        </div>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Displayorder" class="control-label"></label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text">
                                    <i class="fas fa-dollar-sign"></i>
                                </div>
                            </div>
                            <input asp-for="Displayorder" class="form-control" />
                        </div>
                        <span asp-validation-for="Displayorder" class="text-danger"></span>
                    </div>
                </div>
            </div>
            @*<div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BulkyBookWeb/Views/TransactionCategoryModal/Create.cshtml
@model BulkyBookWeb.ViewModels.CreateCategoryViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateCategoryViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Displayorder" class="control-label"></label>
                <input asp-for="Displayorder" class="form-control" />
                <span asp-validation-for="Displayorder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BulkyBookWeb/Views/TransactionCategoryModal/Delete.cshtml
@model BulkyBookWeb.ViewModels.CreateCategoryViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CreateCategoryViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Displayorder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Displayorder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BulkyBookWeb/Views/TransactionCategoryModal/Details.cshtml
@model BulkyBookWeb.ViewModels.CreateCategoryViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CreateCategoryViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Displayorder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Displayorder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BulkyBookWeb/Views/TransactionCategoryModal/Index.cshtml
@model IEnumerable<BulkyBookWeb.Models.Category>

@{
    ViewData["Title"] = "Index";
    
}

<h1 class="text-center"> <i class="fas fa-comment-dollar  text-success"></i>Category Crud</h1>

<p>
    <a onclick="showInPopup('@Url.Action("AddorEdit","TransactionCategoryModal",null,Context.Request.Scheme)','New create category')" class="btn btn-success text-white"><i class="fas fa-random"></i>Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Displayorder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Displayorder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDateTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>