BulkyBookWeb/Controllers/AdministrationController.cs
using BulkyBookWeb.ViewModels.Claims;
using bulkybookweb.ViewModels.Administration;
using BulkyBookWeb.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace BulkyBookWeb.Controllers
{
    //[Authorize(Roles ="Admin")]
    //[Authorize(Policy= "AdminRolePolicy")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
       

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;

        }
        [HttpGet]
        //[Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id ={userId} cannot be found";
                return View("NotFound");
            }
            var existingUserClaims = await userManager.GetClaimsAsync(user);    
            var model = new UserClaimsViewModel
            {
                UserId= userId
            };
            foreach(Claim claim in ClaimsStore.AllClaims)
            {
                UserClaim userClaim = new UserClaim 
                {
                    ClaimType = claim.Type,
                };
                //if the user has the claim,set isselected  property  to true,
                //so the checkbox next to the claim is checked on the UI
                if(existingUserClaims.Any(c => c.Type== claim.Type  && c.Value=="true"))
                {
                    userClaim.IsSelected = true;
                }
                model.Claims.Add(userClaim);
            }
            return View(model);
        }
        [HttpPost]
        //[Authorize(Policy = "EditRolePolicy")]

        public async Task<IActionResult> ManageUserClaims(UserClaimsViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id ={model.UserId} cannot be found";
                return View("NotFound");
            }
            var claims = await userManager.GetClaimsAsync(user);
            var result = await userManager.RemoveClaimsAsync(user, claims);
            if(!result.Succeeded)
            {
                ModelState.AddModelError("","can not remove user existing claims");
                return View(model);
            }
            result = await userManager.AddClaimsAsync(user,
                //model.Claims.Where(c => c.IsSelected).Select(c => new Claim(c.ClaimType,c.ClaimType))) ; we can also use below logic for adding claim type
                model.Claims.Select(c => new Claim(c.ClaimType, c.IsSelected? "true":"false"))) ;
            if(!result.Succeeded)
            {
                ModelState.AddModelError("", "can not add selected claims to user");
                return View(model);
            }
            return RedirectToAction("EditUser" , new { Id= model.UserId});

        }

        [HttpGet]
        [Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> ManageUserRoles(string userId)
        {
            ViewBag.userId= userId;
            var user= await userManager.FindByIdAsync(userId);
            if( user==null)
            {
                ViewBag.ErrorMessage = $"User with Id ={userId} cannot be found";
                return View("NotFound");
            }
            var model = new List<UserRolesViewModel2>();
            foreach(var role in roleManager.Roles)
            {
                var userRolesViewModel = new UserRolesViewModel2 {
                    RoleId=role.Id,
                    RoleName=role.Name
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.IsSelected = true;
                }
                else
                {
                    userRolesViewModel.IsSelected = false;
                }
                model.Add(userRolesViewModel);

            }
            return View(model);
        }
         
        [HttpPost]
        [Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> ManageUserRoles(List<UserRolesViewModel2> model, string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id ={userId} cannot be found";
                return View("NotFound");
            }
            var roles = await userManager.GetRolesAsync(user);
            var result = await userManager.RemoveFromRolesAsync(user,roles);
            if(!result.Succeeded)
            {
                ModelState.AddModelError("","cannot remove user existing roles");
                return View(model);
            }
            result = await userManager.AddToRolesAsync(user,model.Where(x=> x.IsSelected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("EditUser", new { Id= userId});

        }

            [HttpPost]
        public async Task<IActionResult> DeleteUSer(string id)
        {
            char[] removestring = { 'm', 'e', 't', 'h', 'o', 'd', '=' };
            id = id.TrimEnd(removestring);
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with id={id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListUSers");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View("ListUSers");
            }

        }

        [HttpPost]
        [Authorize(Policy ="DeleteRolePolicy")]
        public async Task<IActionResult> DeleteRole(string id)
        {
            //string tempid = id;
            char[] removestring = { 'm', 'e', 't', 'h', 'o', 'd', '=' };
            id = id.TrimEnd(removestring);
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with id={id} cannot be found";
                return View("NotFound");
            }
            else
            {
               try
                {
                    var result = await roleManager.DeleteAsync(role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListRoles");
                    }
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    return View("ListRoles");
                }
                catch (DbUpdateException ex)
                {
                    //logger.LogError($"Error deleting role {ex}");
                    ViewBag.ErrorTitle = $"{ role.Name} role is in use";
                    ViewBag.ErrorMessage = $"{role.Name} role can not be deleted as there are users in this role."+
                        $"If you want to delete this role, please remove users from this role and try to delete again";
                    return View("Error");

                }
            }

        }


        [HttpGet]
        [AllowAnonymous]
        public IActionResult ListUsers()
        {
            var users = userManager.Users;
            return View(users); 
        }
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user=await userManager.FindByIdAsync(id);
          
            if(user == null)
            {
                ViewBag.ErrorMessage = $"User with id = {id} cannot be found";
                return View("NotFound");
            }
            var userClaims= await userManager.GetClaimsAsync(user);
            var userRoles = await userManager.GetRolesAsync(user);
            var model = new EditUserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                City = user.City,
                Claims = userClaims.Select(c =>c.Type + ": " + c.Value).ToList(),
                Roles= userRoles
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                user.Email = model.Email;
                user.City = model.City;
                user.UserName=model.UserName;
                var result = await userManager.UpdateAsync(user);
                if(result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }
                foreach(var error in result.Errors)
                {

BulkyBookWeb/Controllers/CategoryController.cs
using bulkybookweb.efcore;

using BulkyBookWeb.Models;
using BulkyBookWeb.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly EFCategoryRepository eFCategoryRepository;

        public CategoryController(EFCategoryRepository eFCategoryRepository)
        {
            this.eFCategoryRepository = eFCategoryRepository;
        }
        // GET: CategoryController
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var CategoryList = await eFCategoryRepository.GetAll();
            return View(CategoryList);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoryController/Create
        [HttpGet]
      
        public ActionResult Create()
        {
            CreateCategoryViewModel model = new CreateCategoryViewModel();
            return View(model);
        }

        // POST: CategoryController/Create
        [HttpPost]
     

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCategoryViewModel model)
        {

            if (ModelState.IsValid)
            {
                Category newcategory = new Category
                {
                    Name = model.Name,
                    Displayorder = model.Displayorder,
                    // CreatedDateTime = model.CreatedDateTime
                };
                await eFCategoryRepository.Add(newcategory);
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("Index", new { id = newcategory.Id });
            }
            else
            {
                return View();
            }

        }

        // GET: CategoryController/Edit/5
        [HttpGet]
     
        public async Task<IActionResult> Edit(int id)
        {
            var obj = await eFCategoryRepository.Get(id);
            CreateCategoryViewModel model = new CreateCategoryViewModel
            {
                ID = obj.Id,
                Displayorder = obj.Displayorder,
                CreatedDateTime = obj.CreatedDateTime,
                Name = obj.Name
            };

            return View(model);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {

                Category UpdateCategory = await eFCategoryRepository.Get(model.ID);
                UpdateCategory.Displayorder = model.Displayorder;
                UpdateCategory.CreatedDateTime = model.CreatedDateTime;
                //UpdateCategory.ID = model.ID;
                UpdateCategory.Name = model.Name;
                await eFCategoryRepository.Update(UpdateCategory);
                TempData["success"] = "Category Updated Successfully";
                return RedirectToAction("Index");
            }
            else
                return View();
        }

        // GET: CategoryController/Delete/5
        [HttpGet]
       
        public async Task<IActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                var obj = await eFCategoryRepository.Get(id);
                CreateCategoryViewModel model = new CreateCategoryViewModel
                {
                    ID = obj.Id,
                    Displayorder = obj.Displayorder,
                    CreatedDateTime = obj.CreatedDateTime,
                    Name = obj.Name
                };
                return View(model);
            }
            else
                return NotFound();
        }

        // POST: CategoryController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
       

        public async Task<IActionResult> DeletePost(int id)
        {
            var obj = await eFCategoryRepository.Get(id);
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                await eFCategoryRepository.Delete(obj.Id);
                TempData["success"] = "Category deleted Successfully";
                return RedirectToAction("Index");
            }

        }
    }
}

BulkyBookWeb/Controllers/datatableController.cs
using bulkybookweb.efcore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{
    public class datatableController : Controller
    {
        private readonly EFCategoryRepository eFCategoryRepository;

        public datatableController(EFCategoryRepository eFCategoryRepository)
        {
            this.eFCategoryRepository = eFCategoryRepository;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var CategoryList = await eFCategoryRepository.GetAll();
            return View(CategoryList);
        }
    }
}

BulkyBookWeb/Views/Shared/NotFound.cshtml
@{

    ViewBag.Title = "Not Found";
}
<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="Index" asp-controller="Category">Click here to navigate to the Home Page</a>

BulkyBookWeb/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>

    <link rel="stylesheet" href="~/css/bootswatchthem.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href= "//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" /> // adding toastr
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/css/jquery.dataTables.min.css"></script>
    <script src="~/css/dataTables.bootstrap5.css"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;1,100;1,300;1,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link " asp-area="" asp-controller="TransactionCategoryModal" asp-action="Index">CategoryNew</a>
        </li>
         <li class="nav-item">
          <a class="nav-link " asp-area="" asp-controller="datatable" asp-action="Index">CategoryDatatable</a>
        </li>
         <li class="nav-item">
          <a class="nav-link " asp-area="" asp-controller="ManageModalCategory" asp-action="Index">ModalCategory</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " asp-area="" asp-controller="Category" asp-action="Index">Category</a>
        </li>
        
       @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin") ||signInManager.IsSignedIn(User) && User.IsInRole("Super Admin") ){
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Manage</a>
           <div class="dropdown-menu">
            <a class="nav-link " asp-area="" asp-controller="Administration" asp-action="ListUsers">User</a>
            <a class="nav-link " asp-area="" asp-controller="Administration" asp-action="ListRoles">Roles</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-"></div>
            <a class="dropdown-item" href="#">Separated link</a>
           </div>
         </li>
        }
      </ul>
      <ul class="navbar-nav ml-auto" >
          @if(signInManager.IsSignedIn(User))
          {
              <li class="nav-item">
                <form method="post" asp-action="Logout" asp-controller="Account">
                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                        LogOut @User.Identity.Name
                    </button>
                </form>
              </li>
          }
          else
          {
               <li class="nav-item">
                <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">Register</a>
               </li>
                <li class="nav-item">
                <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Login">LogIn</a>
               </li>
          }
          
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>



        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                           
                        </li>
                        <li class="nav-item">
                           
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"></partial>
            @RenderBody()
        </main>
        @if (IsSectionDefined("Scripts"))
        {
            @RenderSection("Scripts", required: true)
        }

    </div>
    
<div class="modal fade" role="dialog" id="formModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable  " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
      </div>
@*      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save</button>
      </div>*@
    </div>
  </div>
</div>

    <div class="loaderbody" id="loaderbody">
     <div class="loader"></div>
    </div>
    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/dataTables.bootstrap5.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/notify.min.js" asp-append-version="true"></script>
   @* @await RenderSectionAsync("Scripts", required: false)*@
</body>
</html>

BulkyBookWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
   
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}