BulkyBookWeb/Controllers/ManageModalCategoryController.cs
using bulkybookweb.efcore;
using BulkyBookWeb.Models;
using BulkyBookWeb.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BulkyBookWeb.Controllers
{
    public class ManageModalCategoryController : Controller
    {
        private readonly EFCategoryRepository eFCategoryRepository;

        public ManageModalCategoryController(EFCategoryRepository eFCategoryRepository)
        {
            this.eFCategoryRepository = eFCategoryRepository;
        }
        // GET: ManageModalCategory
        public async Task<IActionResult> Index()
        {
            var model= await eFCategoryRepository.GetAll();

            return View(model);
        }

        // GET: Transaction/AddOrEdit(Insert)
        // GET: Transaction/AddOrEdit/5(Update)
        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                CreateCategoryViewModel model = new CreateCategoryViewModel();
                return View(model);
            }
                
            else
            {
                var transactionModel = await eFCategoryRepository.Get(id);
                if (transactionModel == null)
                {
                    return NotFound();
                }
                return View(transactionModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("ID,Name,Displayorder,CreatedDateTime")] CreateCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Insert
                if (id == 0)
                {
                    Category newcategory = new Category
                    {
                        CreatedDateTime = DateTime.Now,
                        Name = model.Name,
                        Displayorder = model.Displayorder
                    };
                    var obj = await eFCategoryRepository.Add(newcategory);


                }
                //Update
                else
                {
                    try
                    {
                        Category editcateogry = await eFCategoryRepository.Get(id);
                        editcateogry.Name = model.Name;
                        editcateogry.Displayorder = model.Displayorder;
                        editcateogry.CreatedDateTime = model.CreatedDateTime;
                        await eFCategoryRepository.Update(editcateogry);
                    }
                    catch (Exception ex)
                    {
                        throw ex;
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "Index", eFCategoryRepository.GetAll()) });
            }
            //return null;
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit",model ) });
        }

        // POST: Transaction/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Model =await eFCategoryRepository.Get(id);
            if (Model == null)
                return BadRequest();
            else
            {
                Model = await eFCategoryRepository.Delete(id);
            }
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", eFCategoryRepository.GetAll()) });
        }

    }
    
}

BulkyBookWeb/Views/ManageModalCategory/AddOrEdit.cshtml
@model BulkyBookWeb.ViewModels.CreateCategoryViewModel
@{
    Layout = null;
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.ID" onsubmit="return jQueryAjaxPost(this);" autocomplete="off">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" asp-for="CreatedDateTime" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <div class="input-group-text">#</div>
                    </div>
                    <input asp-for="Name" class="form-control" />
                </div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Displayorder" class="control-label"></label>
                        <input asp-for="Displayorder" class="form-control" />
                        <span asp-validation-for="Displayorder" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="CreatedDateTime" class="control-label"></label>
                        <input asp-for="CreatedDateTime" class="form-control" />
                        <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
                    </div>
                </div>
            </div>
           
            <div class="form-group">
                <div class="col-md-6 offset-md-3">
                    <input type="submit" value="Save" class="btn btn-primary btn-block" />
                </div>
            </div>
        </form>
    </div>
</div>

BulkyBookWeb/Views/ManageModalCategory/CategoryModalPartial.cshtml
@model CreateCategoryViewModel
<div class="Modal fade" id="AddCategory">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4  class="modal-title" id="AddCategoryLabel">Add Category</h4>
                <button type="button" class="close" data-dismiss="modal" >
                    <span>X</span>
                </button>
                </div>
            <div class = "modal-body">
                <form action ="Create">
                    <div class = "form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class = "form-group">
                        <label asp-for="Displayorder" class="control-label"></label>
                        <input asp-for="Displayorder" class="form-control" />
                        <span asp-validation-for="Displayorder" class="text-danger"></span>
                    </div>
                </form></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" style="width:150px" data-save="modal">Create</button>
                <button type="button" class="btn btn-primary" style="width:150px" data-dismiss="modal">Close</button>

                
            </div>
        </div>
    </div>
</div>

BulkyBookWeb/Views/ManageModalCategory/Index.cshtml
@model IEnumerable<BulkyBookWeb.Models.Category>

@{ ViewData["Title"] = "Index"; }

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<!-- Button trigger modal -->
@*<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#formModal">Add Category
</button>

<a onclick="showInPopup('@Url.Action("AddorEdit","ManageModalCategory",null,Context.Request.Scheme)','Add Category')"></a>
*@
<!-- Modal -->
@*<div class="modal fade" id="exampleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable  ">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>*@
@*<div id="PlaceHolderHere"></div>*@

@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Displayorder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Displayorder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDateTime)
            </td>
            <td>
                 <a asp-action="Edit" asp-controller="ManageModalCategory" asp-route-id="@item.Id"
                       class="btn btn-primary mx-2" > <i class="bi bi-pencil-square"></i>
                           Edit</a>|
                
                <a asp-action="Delete" asp-controller="ManageModalCategory" asp-route-id="@item.Id"
                       class="btn btn-primary mx-2" > <i class="bi bi-pencil-square"></i>
                           Delete</a>|
            </td>
        </tr>
}
    </tbody>
</table>*@
@*@section Scripts{ 
    <script src="~/js/CustomScripts.js"></script>
}*@

BulkyBookWeb/Views/ManageModalCategory/_ViewAll.cshtml
@model IEnumerable<BulkyBookWeb.Models.Category>
@{
    ViewBag.Title = "I am Abid ";
}
<h1 class="text-center"><i class="fas fa-comments-dollar text-success"></i> Category History</h1>


<table class="table">
    <thead class="thead-light">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Displayorder)
            </th>
            
            <th>
                <a onclick="showInPopup('@Url.Action("AddorEdit","ManageModalCategory",null,Context.Request.Scheme)','New Category')" class="btn btn-success text-white"><i class="fas fa-random"></i> New Cateogry</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Displayorder)
                </td>
                
                <td>
                    <div>
                        <a onclick="showInPopup('@Url.Action("AddOrEdit","ManageModalCategory",new {id=item.Id},Context.Request.Scheme)','Update Category')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                        <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                            <input type="submit" value="Delete" class="btn btn-danger"/>
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{ 
    <script src="~/js/CustomScripts.js"></script>
}